### ISSUE TITLE
Importing picoweb fails on ESP8266

### ISSUE THREAD

**Issue by calston** [pfalcon/picoweb#9] opened 2017-04-21 12:18 UTC
At `import picoweb`

MemoryError: memory allocation failed, allocating 554 bytes

MicroPython v1.8.7-7-gb5a1a20a3 on 2017-01-09; ESP module with ESP8266

**Comment by pfalcon** [comment] 2017-04-21 12:29
Duplicate of https://github.com/pfalcon/picoweb/issues/4

**Closed as completed by pfalcon** 2017-04-21 12:29 UTC
