### ISSUE TITLE
Server crashes as the route is accessed

### ISSUE THREAD

**Issue by besi** [pfalcon/picoweb#46] opened 2019-01-16 22:23 UTC
I have a very simple picoserver setup:

```python
import picoweb
app = picoweb.WebApp(__name__)

@app.route("/")
def index(req, resp):
    yield from picoweb.start_response(resp)
    yield from resp.awrite("This is webapp #2")

app.run(debug=True, current_ip)
```

Then I see:

> * Running on <http://192.168.1.125:8081/>

So the webserver did start. However, as soon as I click the link and access it in the browser. I get the crash:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/picoweb/__init__.py", line 298, in run
  File "/lib/uasyncio/core.py", line 155, in run_forever
  File "/lib/uasyncio/core.py", line 130, in run_forever
  File "/lib/uasyncio/__init__.py", line 60, in remove_writer
TypeError: function takes 2 positional arguments but 3 were given
```

I am running this on a ESP32 using the latest `esp32-20190113-v1.9.4-779-g5064df207.bin` firmware.

**Comment by pfalcon** [comment] 2019-01-17 05:54
Duplicate of https://github.com/pfalcon/picoweb/issues/45

**Closed as completed by pfalcon** 2019-01-17 05:54 UTC
