### ISSUE TITLE
TypeError: function expected at most 3 arguments, got 4

### ISSUE THREAD

**Issue by joseshiru** [pfalcon/picoweb#62] opened 2020-01-20 14:10 UTC
Hi guys,

I'm running the basic example of the picoweb in a ESP32 with MicroPython v1.12, and I'm getting this error:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "/lib/picoweb/__init__.py", line 311, in run
  File "/lib/picoweb/__init__.py", line 293, in serve
  File "/lib/uasyncio/core.py", line 129, in run_forever
  File "/lib/uasyncio/__init__.py", line 32, in add_reader
TypeError: function expected at most 3 arguments, got 4

====== 
 File "main.py", line 20, in <module> is "app.run(debug=True)"

Thanks

**Comment by pfalcon** [comment] 2020-01-21 10:08
Duplicate of https://github.com/pfalcon/picoweb/issues/45

**Closed as completed by pfalcon** 2020-01-21 10:08 UTC
