### ISSUE TITLE
failed to install on micropython-esp using upip

### ISSUE THREAD

**Issue by fruch** [pfalcon/picoweb#13] opened 2017-07-24 15:16 UTC
I'm really new to micropython and trying to install this package with upip:

    import upip
    upip.install('picoweb')

and it keep failing saying the package is partly installed

**Comment by pfalcon** [comment] 2017-10-31 13:42
Try after reset.

**Comment by larsks** [comment] 2017-11-10 13:30
@pfalcon I thought that picoweb didn't work on esp8266 boards (#4, #9)? Or has that changed? Because if it has, I'm having the same problem as @fruch.

**Comment by pfalcon** [comment] 2017-11-10 13:37
@larsks: See https://github.com/pfalcon/notes-pico#deploying-on-embedded-micropython-targets

**Comment by larsks** [comment] 2017-11-10 13:40
@pfalcon Thanks for the reference!

**Comment by flyboy74** [comment] 2017-11-20 01:03
I am trying to get picoweb running on my ESP8266. I was quite sure how to follow pfalcon link.
I installed esp8266-20171101-v1.9.3.bin and have connected via serial tt to micropython and connected to my Wifi router and started WebREPL successfully. But have been unable to install Picweb. Do I need a different firmware??

**Comment by fruch** [comment] 2017-11-20 05:15
@flyboy74 follow the instructions from @pfalcon notes. 

thing is that the esp8266 doesn't have enough memory for the upip to download "big" packages correctly. (big is not the files, but responses from pypi)

the best thing todo is to download micropython source and build the need packages into the image.

**Comment by flyboy74** [comment] 2017-11-20 06:09
Thanks I now understand the problem. Now for me to understand the work around. I used my windows PC to flash the BIN file to the ESP8266 using ESP8226flasher but I do also have esptool.py downloaded. All the instructions seem to be for a linux machine. Can I install picoweb from my windows machine??

**Comment by flyboy74** [comment] 2017-11-20 06:11
I do own Raspberry pi. Will it be easier to install from my RPi

**Comment by flyboy74** [comment] 2017-11-20 06:28
Also I was wondering if picoweb can in future be included in standard installation of micropython for ESP chips considering the purpose that ESP chip are used for

**Comment by fruch** [comment] 2017-11-20 06:41
I would recommend building on a VM (install virtualbox) or on a docker instance. maybe things in win10 improved and you can use the new linux distro in windows, but I never used it, so can't say how easy it is to work with it.

**Comment by flyboy74** [comment] 2017-11-20 06:54
sounds hard especially since my SSD drive is nearly full on my PC. I have ordered a ESP32 dev board and I believe it has the capacity to install picoweb using upip. I might have to wait till it arrives might be easier.

**Comment by flyboy74** [comment] 2017-11-20 06:56
Where's the best place for me to raise the issue of having picoweb prebuilt into the micropyton BIN file for the ESP boards especially the ESP8266

**Comment by pfalcon** [comment] 2018-01-30 11:36
> Where's the best place for me to raise the issue of having picoweb prebuilt into the micropyton BIN file for the ESP boards especially the ESP8266

There're (hopefully) thousands of MicroPython users and each of them wants their favorite modules to be embedded. However, that doesn't scale: if we add all those modules, the binary won't fit on any board out there. That's why (Micro)Python uses modular approach instead. Yes, using it requires some learning, but that's true about anything in Computer Science/Information Technologies. MicroPython is open-source project, so it's important that people actually exercised their right to use and deal with source, or it's all failure. Please don't make our beloved project a failure ;-).

Btw, there's now summarized docs on dealing with various aspects of uPy application deployment: http://pycopy.readthedocs.io/en/latest/reference/packages.html .

**Comment by pfalcon** [comment] 2018-01-30 11:38
Other, the original issue in the title doesn't seem to be reproducible (but certainly can be a transient failure).

So, I'm closing this, feel free to open a new ticket with detailed information about your setup and steps to reproduce.

**Closed as completed by pfalcon** 2018-01-30 11:38 UTC
